### ISSUE TITLE
It called me a bitch 

### ISSUE THREAD

**Issue by NOTDANKTANK** [jimmyy4/BorpBot#19]
It called me a bitch and that hurt my feelings 
![IMG_20230314_011848](https://user-images.githubusercontent.com/127843327/224966948-0d579d87-adff-47ac-89dc-2ae08a8db410.jpg)

**Comment by Hexugory** [comment]
you probably deserved it, closed

**Comment by james7132** [comment]
This is against GitHub's ToS. Super toxic. Please add a more inclusive Code of Conduct to this project.
